# Generated by Django 6.1.1 on 2026-10-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('idcentro', models.AutoField(db_column='IdCentro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreCentro', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'centros',
            },
        ),
        migrations.CreateModel(
            name='DispositivosTipo',
            fields=[
                ('idtipodispositivo', models.AutoField(db_column='IdTipoDispositivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoDispositivo', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'dispositivos_tipo',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('idtipodocumento', models.AutoField(db_column='IdTipoDocumento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoDocumento', max_length=30)),
            ],
            options={
                'db_table': 'documento_tipo',
            },
        ),
        migrations.CreateModel(
            name='FichasNombre',
            fields=[
                ('idfichanombre', models.AutoField(db_column='IdFichaNombre', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreFicha', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fichas_nombre',
            },
        ),
        migrations.CreateModel(
            name='FichasTipo',
            fields=[
                ('idtipoficha', models.AutoField(db_column='IdTipoFicha', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoFicha', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'fichas_tipo',
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('idingreso', models.AutoField(db_column='IdIngreso', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FechaIngreso')),
                ('horaingreso', models.TimeField(db_column='HoraIngreso')),
            ],
            options={
                'db_table': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idjornada', models.AutoField(db_column='IdJornada', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreJornada', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'jornada',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreRol', max_length=20, unique=True)),
                ('descripcion', models.TextField(db_column='DescripcionRol')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='VehiculosMarca',
            fields=[
                ('idmarcavehiculo', models.AutoField(db_column='IdMarcaVehiculo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreMarcaVehiculo', max_length=20)),
            ],
            options={
                'db_table': 'vehiculos_marca',
            },
        ),
        migrations.CreateModel(
            name='VehiculosTipo',
            fields=[
                ('idtipovehiculo', models.AutoField(db_column='IdTipoVehiculo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoVehiculo', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'vehiculos_tipo',
            },
        ),
        migrations.CreateModel(
            name='DispositivosMarca',
            fields=[
                ('idmarcadispositivo', models.AutoField(db_column='IdMarcaDispositivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreMarcaDispositivo', max_length=20)),
                ('tipo', models.ForeignKey(db_column='IdTipoDispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.dispositivostipo')),
            ],
            options={
                'db_table': 'dispositivos_marca',
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('iddispositivo', models.AutoField(db_column='IdDispositivo', primary_key=True, serialize=False)),
                ('sn', models.CharField(db_column='SnDispositivo', max_length=50, unique=True)),
                ('documento', models.FileField(blank=True, db_column='DocumentoDispositivo', max_length=50, null=True, upload_to='docs/devices/')),
                ('marca', models.ForeignKey(db_column='IdMarcaDispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.dispositivosmarca')),
                ('tipo', models.ForeignKey(db_column='IdTipoDispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.dispositivostipo')),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
        migrations.CreateModel(
            name='IngresosDispositivos',
            fields=[
                ('idingresodispositivo', models.AutoField(db_column='IdIngresoDispositivo', primary_key=True, serialize=False)),
                ('dispositivo', models.ForeignKey(db_column='IdDispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.dispositivos')),
                ('ingreso', models.ForeignKey(db_column='IdIngreso', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.ingresos')),
            ],
            options={
                'db_table': 'ingresos_dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('idficha', models.AutoField(db_column='IdFicha', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='NumeroFicha', max_length=10, unique=True)),
                ('centro', models.ForeignKey(db_column='IdCentro', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.centros')),
                ('nombre', models.ForeignKey(db_column='IdNombreFicha', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.fichasnombre')),
                ('tipo', models.ForeignKey(db_column='IdTipoFicha', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.fichastipo')),
                ('jornada', models.ForeignKey(db_column='IdJornada', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.jornada')),
            ],
            options={
                'db_table': 'fichas',
            },
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('idsalida', models.AutoField(db_column='IdSalida', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FechaSalida')),
                ('horasalida', models.TimeField(db_column='HoraSalida')),
                ('ingreso', models.ForeignKey(db_column='IdIngreso', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.ingresos')),
            ],
            options={
                'db_table': 'salidas',
            },
        ),
        migrations.CreateModel(
            name='SalidasDispositivos',
            fields=[
                ('idsalidadispositivo', models.AutoField(db_column='IdSalidaDispositivo', primary_key=True, serialize=False)),
                ('dispositivo', models.ForeignKey(db_column='IdDispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.dispositivos')),
                ('salida', models.ForeignKey(db_column='IdSalida', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.salidas')),
            ],
            options={
                'db_table': 'salidas_dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='NombresUsuario', max_length=50)),
                ('apellidos', models.CharField(db_column='ApellidosUsuario', max_length=50)),
                ('documento', models.CharField(db_column='DocumentoUsuario', max_length=10, unique=True)),
                ('telefono', models.CharField(db_column='TelefonoUsuario', max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, db_column='CorreoUsuario', max_length=100, null=True, unique=True)),
                ('centro', models.ForeignKey(blank=True, db_column='IdCentro', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.centros')),
                ('ficha', models.ForeignKey(blank=True, db_column='IdFicha', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.fichas')),
                ('rol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.roles')),
                ('tipodocumento', models.ForeignKey(db_column='IdTipoDocumento', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.documentotipo')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='ingresos',
            name='usuario',
            field=models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.usuarios'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='usuario',
            field=models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.usuarios'),
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('idvehiculo', models.AutoField(db_column='IdVehiculo', primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, db_column='PlacaVehiculo', max_length=7, null=True, unique=True)),
                ('modelo', models.CharField(blank=True, db_column='ModeloVehiculo', default=None, max_length=4, null=True)),
                ('usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.usuarios')),
                ('marca', models.ForeignKey(db_column='IdMarcaVehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.vehiculosmarca')),
                ('tipo', models.ForeignKey(db_column='IdTipoVehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.vehiculostipo')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.AddField(
            model_name='salidas',
            name='vehiculo',
            field=models.ForeignKey(blank=True, db_column='IdVehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.vehiculos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='vehiculo',
            field=models.ForeignKey(blank=True, db_column='IdVehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.vehiculos'),
        ),
        migrations.AddField(
            model_name='vehiculosmarca',
            name='tipo',
            field=models.ForeignKey(db_column='IdTipoVehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.vehiculostipo'),
        ),
    ]
